from keyboard.first_keyboard import first_keyboard
from keyboard.student_keyboard import st_keyboard
from keyboard.teacher_keyboard import tch_keyboard
from keyboard.admin_keyboard import adm_keyboard
from keyboard.material_keyboard import mtrl_keyboard
from keyboard.file_keyboard import fl_keyboard
from keyboard.announcement_keyboard import ab_keyboard
from keyboard.poll_keyboard import pb_keyboard